Models/ErrorViewModel.cs
namespace SmartSchools.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/TeachersTest.cs
using System.ComponentModel.DataAnnotations;

namespace SmartSchools.Models
{
    public class TeachersTest
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Controllers/API/LanguageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;

namespace SmartSchools.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class LanguageController : ControllerBase
    {
        private readonly IStringLocalizer<LanguageController> _Localizer;

        public LanguageController(IStringLocalizer<LanguageController> Localizer)
        {
            _Localizer = Localizer;
        }

        [HttpGet]
        public IActionResult Get()
        {
            return Ok(_Localizer["Welcome"].Value);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SmartSchools.Models;
using System.Diagnostics;

namespace SmartSchools.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Questions()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/QuestionsController.cs
using Microsoft.AspNetCore.Mvc;

namespace SmartSchools.Controllers
{
    public class QuestionsController : Controller
    {
        private IWebHostEnvironment hostingEnv;

        public QuestionsController(IWebHostEnvironment env)
        {
            this.hostingEnv = env;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upload(IFormFile file)

        {
            string x = HttpContext.Session.GetString("IsMain");
            var FileDic = "Temp";
            string SubFileDic = Guid.NewGuid().ToString();
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("SubFolderName")))
            {
                SubFileDic = HttpContext.Session.GetString("SubFolderName").ToString();
            }
            else
            {
                HttpContext.Session.SetString("SubFolderName", SubFileDic);
            }

            string FilePath = Path.Combine(hostingEnv.WebRootPath, FileDic);

            if (!Directory.Exists(FilePath))
                Directory.CreateDirectory(FilePath);
            string SubFilePath = Path.Combine(FilePath, SubFileDic);
            if (!Directory.Exists(SubFilePath))
                Directory.CreateDirectory(SubFilePath);
            var fileName = file.FileName;

            if (x == "yes")
                fileName = $"Main_{fileName}";

            string filePath = Path.Combine(SubFilePath, fileName);
            using (FileStream fs = System.IO.File.Create(filePath))
            {
                file.CopyTo(fs);
            }



            return RedirectToAction("Index");




            //delete Folder
            //string path = @"D:\Workarea\Test\Code";
            //Directory.Delete(path);


            //Move Folder from source to destination
            //string source = @"D:\Workarea\Test\Code";
            //string destination = @"D:\Workarea\Test\NewDirectory";

            //try
            //{
            //    // First, you should ensure that the
            //    // source directory exists
            //    if (Directory.Exists(source))
            //    {
            //        // You should eEnsure the destination
            //        // directory doesn't already exist
            //        if (!Directory.Exists(destination))
            //        {
            //            // Move the source directory
            //            // to the new location
            //            Directory.Move(source, destination);
            //        }
            //        else
            //        {
            //            Console.WriteLine("Destination directory" +
            //                        " already exists...");
            //        }
            //    }
            //    else
            //    {
            //        Console.WriteLine("Source directory " +
            //                "does not exist...");
            //    }
            //}
            //catch (Exception ex)
            //{
            //    Console.WriteLine(ex.Message);
            //}
        }

        [HttpPost]
        public IActionResult SetIsMain(string IsMain)
        {
            HttpContext.Session.SetString("IsMain", IsMain);
            string x = HttpContext.Session.GetString("IsMain");
            return Json(HttpContext.Session.GetString("IsMain"));
        }

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/Questions.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Questions/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!doctype html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  
</head>
<style>
    .input-group-append {
        cursor: pointer;
    }
</style>
<div class="row">
    <div class="col-md-8 offset-md-2">
        <form>
            <row>
                <label>Teacher:</label>
                <select class="form-select" style="width: 50%" aria-label="Default select example">
                    <option selected>-Select-</option>
                    <option value="1">Ahmed Othman</option>
                    <option value="2">Mohammed Karim</option>
                    <option value="3">Ayman Ahmed</option>
                </select>
            </row>
            <row>
                <label>Class:</label>
                <select class="form-select" style="width: 50%" aria-label="Default select example">
                    <option selected>-Select-</option>
                    <option value="1">A1</option>
                    <option value="2">B2</option>
                    <option value="3">C3</option>
                </select>
            </row>
            <row>
                <label>Subject:</label>
                <select class="form-select" style="width: 50%" aria-label="Default select example">
                    <option selected>-Select-</option>
                    <option value="1">Chemistry</option>
                    <option value="2">Computer Science</option>
                    <option value="3">Math</option>
                </select>
            </row>
            <row>
                <label>Title:</label>
                <input type="text" class="form-control" style="width: 50%" />
            </row>
            <row>
                <label>Lesson Type:</label>
                <select class="form-select" style="width: 50%" aria-label="Default select example">
                    <option selected>-Select-</option>
                    <option value="1">Record</option>
                    <option value="2">Live</option>
                </select>
            </row>
            <row>
                <label for="date" class="col-1 col-form-label">Date:</label>
                <div class="col-5">
                    <i class="bi bi-calendar-date input-group-text"></i>
                    <input type="date" id="datepicker2" class="datepicker_input form-control" placeholder="DD/MM/YYYY">
                </div>
            </row>
            <row>
                <label>Remarks:</label>
                <div class="input-group">
                    <span class="input-group-text">Input</span>
                    <textarea class="form-control" aria-label="Input"></textarea>
                </div>
            </row>
            <row>
                <label>Attachments:</label>
                <div class="input-group mb-3">
                    @*<input type="file" class="form-control" id="inputGroupFile02">
                        <label class="input-group-text" for="inputGroupFile02">Upload</label>*@
                    <form id="form2" method="post" enctype="multipart/form-data" data-parsley-validate class="form-horizontal form-label-left">
                        @* <div class="form-group">*@
                        <div class="col-md-12 border border-info" id="dropzone">
                            <div action="/Questions/Upload" class="dropzone" id="uploader">
                                <div class="dz-message needsclick">
                                    <i class="bi bi-file-earmark-arrow-up text-primary fs-3x"></i>
                                    <div class="ms-4">
                                        <h3 class="fs-5 fw-bolder text-gray-900 mb-1">Drop files here or click to upload.</h3>
                                        <span class="fs-7 fw-bold text-gray-400">Upload up to 10 files</span>
                                    </div>
                                </div>

                            </div>
                        </div>
                        @* </div>*@
                    </form>
                </div>
            </row>
            <row>
                <label>Question:</label>
                <input type="text" class="form-control" style="width: 50%" />
            </row>
            <row>
                <label>Answer Type:</label>
                <select class="form-select" style="width: 50%" aria-label="Default select example">
                    <option selected>-Select-</option>
                    <option value="1">Options</option>
                    <option value="2">Checkbox</option>
                    <option value="3">Written</option>
                    <option value="4">Spoken</option>
                    <option value="5">Attachment</option>
                </select>
            </row>
            <row>
                <label>Question:</label>
                <input type="time" step="3600000" class="form-control" style="width: 50%" />
            </row>
            <row>
                <table class="table table-striped table-dark table-bordered border-light pt-2 mt-2">
                    <thead>
                        <tr style="text-align: center;">
                            <th>No</th>
                            <th>Answer</th>
                            <th>Is Correct</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td style="text-align: center;">1</td>
                            <td></td>
                            <td style="text-align: center;"><input class="form-check-input" type="checkbox"></td>
                        </tr>
                        <tr>
                            <td style="text-align: center;">2</td>
                            <td></td>
                            <td style="text-align: center;"><input class="form-check-input" type="checkbox"></td>
                        </tr>
                        <tr>
                            <td style="text-align: center;">3</td>
                            <td></td>
                            <td style="text-align: center;"><input class="form-check-input" type="checkbox"></td>
                        </tr>
                    </tbody>
                </table>
            </row>
            <row>
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Questions & Answers
                </button>

                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Questions & Answers</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <table class="table table-striped table-dark table-bordered border-light pt-2 mt-2">
                                    <thead>
                                        <tr style="text-align: center;">
                                            <th>No</th>
                                            <th>Answer</th>
                                            <th>Is Correct</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td style="text-align: center;">1</td>
                                            <td></td>
                                            <td style="text-align: center;"><input class="form-check-input" type="checkbox"></td>
                                        </tr>
                                        <tr>
                                            <td style="text-align: center;">2</td>
                                            <td></td>
                                            <td style="text-align: center;"><input class="form-check-input" type="checkbox"></td>
                                        </tr>
                                        <tr>
                                            <td style="text-align: center;">3</td>
                                            <td></td>
                                            <td style="text-align: center;"><input class="form-check-input" type="checkbox"></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="button" class="btn btn-primary">Save changes</button>
                            </div>
                        </div>
                    </div>
                </div>
            </row>
        </form>
    </div>
</div>
</html>

<script>
        $(document).ready( function () {
        $('#myTable').DataTable();
    } );

        /* Bootstrap 5 JS included */
        /* vanillajs-datepicker 1.1.4 JS included */
        const getDatePickerTitle = elem => {
          // From the label or the aria-label
          const label = elem.nextElementSibling;
          let titleText = '';
          if (label && label.tagName === 'LABEL') {
            titleText = label.textContent;
          } else {
            titleText = elem.getAttribute('aria-label') || '';
          }
          return titleText;
        }

        const elems = document.querySelectorAll('.datepicker_input');
        for (const elem of elems) {
          const datepicker = new Datepicker(elem, {
            'format': 'dd/mm/yyyy', // UK format
            title: getDatePickerTitle(elem)
          });
        }

        Dropzone.options.uploader = {
            init: function () {
                this.on("addedfile", function (file) {
                    if (confirm("is this the main Video?")) {
                        $.ajax({
                            type: "POST",
                            url: "/Questions/SetIsMain",
                            data: { "IsMain": "yes" },
                            success: function (response) {
                            },
                            failure: function (response) {
                                alert(response.responseText);
                            },
                            error: function (response) {
                                alert(response.responseText);
                            }
                        });
                    } else {
                        $.ajax({
                            type: "POST",
                            url: "/Questions/SetIsMain",
                            data: { "IsMain": "no" },
                            success: function (response) {
                            },
                            failure: function (response) {
                                alert(response.responseText);
                            },
                            error: function (response) {
                                alert(response.responseText);
                            }
                        });
                    }
                });
            }
        };

</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Smart Schools</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SmartSchools.styles.css" asp-append-version="true" />
    <!-- Font Awesome CSS -->
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css'>
    <!-- Vanilla Datepicker CSS -->
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.1.4/dist/css/datepicker.min.css'>
     <link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css" />
    <!-- Vanilla Datepicker JS -->
    <script src='https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.1.4/dist/js/datepicker-full.min.js'></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <!-- CDN's for datatable js' -->
    <script src='https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css'></script>
    <script src='https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js'></script>
    <script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/dt-1.11.5/r-2.2.9/sl-1.3.4/datatables.min.css"/>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/dt-1.11.5/r-2.2.9/sl-1.3.4/datatables.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Smart Schools</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Questions" asp-action="Index">Questions</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Smart Schools
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
   
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>